apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mqqs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-mcombi-tenant/mqqs/mqqs@sha256:e2be89d78eb4c384a1c8a292e2227ffa5197e1e7fb4d0b6ab1b85b15db2038ab
        name: my-java-quarkus
        resources: {}
status: {}
