apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mqqs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqqs
    app.kubernetes.io/part-of: mqqs
  name: mqqsifix
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: mqqs
    weight: null
status: {}
