apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mqqs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqqs
    app.kubernetes.io/part-of: mqqs
  name: mqqs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: mqqs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: mqqs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-mcombi-tenant/mqqs/mqqs@sha256:2fc8fae0703c600eda49d3c1d5f46f9a26e1da1538b0119ef799b079a0fe9dfd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
