apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mqqs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqqs
    app.kubernetes.io/part-of: mqqs
  name: mqqs
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: mqqs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: mqqs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-mcombi-tenant/mqqs/mqqs@sha256:e2be89d78eb4c384a1c8a292e2227ffa5197e1e7fb4d0b6ab1b85b15db2038ab
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
